version: '3.8'

#services:
#  merchandise-service:
#    build: /
#    hostname: merchandise-service
#    ports:
#      - "8080:80"
#    #restart: always

services:
  merchandise-service:
    build: 
      context: .
      dockerfile: ./Dockerfile
    hostname: merchandise-service
    ports:
      - "5070:5000"
      - "5072:5002"
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5426;Database=merchandise-service;Username=postgres;Password=merchPassword"
    #restart: always
    depends_on:
      - merchandise-service-db

  merchandise-service-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchPassword
      POSTGRES_DB: merchandise-service
    command: "-c log_statement=all"
      
#  emailing-service:
#    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
#    #hostname: emailing-service
#    ports:
#      - "8081:80"
#    #restart: always
#    
#  stock-api:
#    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
#    #hostname: stock-api
#    ports:
#      - "8082:80"  
#    #restart: always
#      
#  supply-service:
#    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
#    #hostname: supply-service
#    ports:
#      - "8083:80"
#    #restart: always
#        
#  employees-service:
#    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
#    #hostname: employees-service
#    ports:
#      - "8084:80"
#    #restart: always
    
    